import React from 'react';
import type { Metadata } from "next";
import Head from 'next/head'
import {
  QueryClientProvider,
} from '@tanstack/react-query';
// import localFont from "next/font/local";
import "./globals.css";
import { queryClient } from "../../react-query/queryClient";
import AlertContextProvider from "../../context/AlertContext";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Largest Cities",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider client={queryClient}>
      <AlertContextProvider>
        <html lang="en">
          <Head>
            <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta>
          </Head>
          <body
          // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </html>
      </AlertContextProvider>
    </QueryClientProvider>
  );
}
